version: '2'

services:
  db:
    image: postgres
  api:
    build: .
    restart: always
    entrypoint: python docker/local.py
    volumes:
      - ./backend:/AnonymousDrChat
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  node:
    command: sh -c "npm install && npm start"
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
volumes:
  node_modules: